#include <stdlib.h>
#include <stdio.h>

#define CC "gcc "
#define CFLAGS "-Wall -Wextra -Wpedantic -Wimplicit-fallthrough --std=c89 "

int main(int argc, char ** argv) {
    
    if(system(CC CFLAGS "example.c -o example") != 0) return 1;
    if(system("./example") != 0) return 1;
    if(system(CC CFLAGS " -c autogenerated.c -o autogenerated.o") != 0) return 1;
    
    return 0;
}
