#define CORE_IMPLEMENTATION
#include "core.h"

#ifndef STAGE_1
#    include "autogenerated.c"
#endif /* !STAGE_1 */

int main(void) {
#ifdef STAGE_1
    FILE * fp = fopen("autogenerated.c", "w");
    core_staged_vec_generate(fp, "example_", "int");
    fclose(fp);
#else
    example_IntVec v = {0};

    example_intvec_append_n_times(&v, 0xFF, 1000);
    assert(v.len == 1000);
    example_intvec_append(&v, 11);
    assert(v.items[100] == 0xFF);
    assert(v.items[1000] == 11);
    printf("%d\n", v.items[123]);
    
    example_intvec_free(&v);
#endif /* STAGE_1 */
    return 0;
}
