#define CORE_STRIP_PREFIX
#define CORE_IMPLEMENTATION
#include "core.h"

#ifdef STAGE_1
void stage_1(void);

int main(void) {
    stage_1();
    return 0;
}
#endif /*STAGE_1*/


#ifndef STAGE_1
#include "autogenerated.c"

int main() {
    example_IntVec v = {0};
    example_intvec_append_n_times(v, 0xFF, 1000);

    example_intvec_free(&v);
    return 0;
}
#endif /*STAGE_1*/

void stage_1(void) {
    FILE * fp = fopen("autogenerated.c", "w");
    core_defer(cleanup) {
        fclose(fp);
    }

    fprintf(fp, "#include <stddef.h>\n");
    fprintf(fp, "#include <stdio.h>\n");
    fprintf(fp, "\n");

    fprintf(fp, "typedef FILE * FileHandle;\n");
    fprintf(fp, "typedef unsigned int uint;\n");
    fprintf(fp, "typedef unsigned short ushort;\n");
    fprintf(fp, "typedef unsigned long ulong;\n");
    fprintf(fp, "typedef unsigned char uchar;\n");
    fprintf(fp, "typedef signed char ichar;\n");
    fprintf(fp, "typedef int boolean;\n");
    fprintf(fp, "\n");

    core_staged_sset_generate(fp, "example_", "const char *");
    
    core_staged_slice_generate(fp, "example_", "int");
    core_staged_slice_generate(fp, "example_", "short");
    core_staged_slice_generate(fp, "example_", "long");
    core_staged_slice_generate(fp, "example_", "char");
    core_staged_slice_generate(fp, "example_", "float");
    core_staged_slice_generate(fp, "example_", "double");
    core_staged_slice_generate(fp, "example_", "size_t");
    core_staged_slice_generate(fp, "example_", "ptrdiff_t");
    core_staged_slice_generate(fp, "example_", "uint");
    core_staged_slice_generate(fp, "example_", "ushort");
    core_staged_slice_generate(fp, "example_", "uchar");
    core_staged_slice_generate(fp, "example_", "ichar");
    core_staged_slice_generate(fp, "example_", "boolean");
    core_staged_slice_generate(fp, "example_", "FileHandle");

    core_staged_vec_generate(fp, "example_", "int");
    core_staged_vec_generate(fp, "example_", "short");
    core_staged_vec_generate(fp, "example_", "long");
    core_staged_vec_generate(fp, "example_", "char");
    core_staged_vec_generate(fp, "example_", "float");
    core_staged_vec_generate(fp, "example_", "double");
    core_staged_vec_generate(fp, "example_", "size_t");
    core_staged_vec_generate(fp, "example_", "ptrdiff_t");
    core_staged_vec_generate(fp, "example_", "uint");
    core_staged_vec_generate(fp, "example_", "ushort");
    core_staged_vec_generate(fp, "example_", "uchar");
    core_staged_vec_generate(fp, "example_", "ichar");
    core_staged_vec_generate(fp, "example_", "boolean");
    core_staged_vec_generate(fp, "example_", "FileHandle");


    core_deferred(cleanup);


}
