#define CORE_IMPLEMENTATION
#include "core.h"

#ifndef STAGE_1
#    include "autogenerated.c"
#endif /* !STAGE_1 */

int main(void) {
#ifdef STAGE_1
    FILE * fp = fopen("autogenerated.c", "w");
    const char * field_names[] = {
        "int",
        "float",
        "bool"
    };
    core_staged_enum_generate(fp, "example_", "tag", CORE_ARRAY_LEN(field_names), field_names);
    core_staged_vec_generate(fp, "example_", "int");
    core_staged_sset_generate(fp, "example_", "const char *");
    fclose(fp);
#else
    example_IntVec v = {0};
    example_ConstCharPtrSSet s = {0};
    const char * data = NULL;
    unsigned long i = 0;
    CORE_DEFER(cleanup) {
        example_constcharptrsset_free(&s);
        example_intvec_free(&v);
        printf("TESTS COMPLETED SUCCESSFULLY!\n");
    }

    /* VEC */
    example_intvec_append_n_times(&v, 0xFF, 1000);
    assert(v.len == 1000);
    example_intvec_append(&v, 11);
    assert(v.items[100] == 0xFF);
    assert(v.items[1000] == 11);
    assert(example_intvec_pop(&v) == 11);
    assert(v.len == 1000);

    /* SSET */
    example_constcharptrsset_insert(&s, 10, "10");
    
    assert(example_constcharptrsset_get(&s, 10, &data) == 0);
    assert(strcmp(data, "10") == 0);
    assert(example_constcharptrsset_get(&s, 11, &data) == 1);
    assert(example_constcharptrsset_get(&s, 100, &data) == 1);
    assert(example_constcharptrsset_get(&s, 10000, &data) == 1);
    assert(s.dense.len == 1);
    
    example_constcharptrsset_insert(&s, 100, "100");
    assert(example_constcharptrsset_get(&s, 10, &data) == 0);
    assert(strcmp(data, "10") == 0);
    assert(example_constcharptrsset_get(&s, 11, &data) == 1);
    assert(example_constcharptrsset_get(&s, 100, &data) == 0);
    assert(strcmp(data, "100") == 0);
    assert(example_constcharptrsset_get(&s, 10000, &data) == 1);
    assert(s.dense.len == 2);
    assert(s.dense_to_sparse.len == 2);
    
    example_constcharptrsset_remove(&s, 10);
    assert(s.dense.len == 1);
    assert(s.dense_to_sparse.len == 1);
    assert(example_constcharptrsset_get(&s, 10, &data) == 1);
    assert(example_constcharptrsset_get(&s, 11, &data) == 1);
    assert(example_constcharptrsset_get(&s, 100, &data) == 0);
    assert(strcmp(data, "100") == 0);
    assert(example_constcharptrsset_get(&s, 10000, &data) == 1);

    for(i = 0; i < 1000; ++i) {
        example_constcharptrsset_insert(&s, i * 3, "foo");
    }
    assert(s.dense.len == 1001);
    assert(s.dense_to_sparse.len == 1001);
    for(i = 0; i < 1000 * 3; ++i) {
        if(i % 3 == 0) {
            assert(example_constcharptrsset_get(&s, i, &data) == 0);
            assert(strcmp(data, "foo") == 0);
        } else {
            if(i == 100) {
                assert(example_constcharptrsset_get(&s, 100, &data) == 0);
                assert(strcmp(data, "100") == 0);
            } else {
                assert(example_constcharptrsset_get(&s, i, &data) == 1);
            }
        }
    }

    example_constcharptrsset_remove(&s, 1500);
    assert(example_constcharptrsset_get(&s, 1500, &data) == 1);
    assert(s.dense.len == 1000);

    CORE_DEFERRED(cleanup);
#endif /* STAGE_1 */
    return 0;
}
