CFLAGS= -Wall -Wextra -Wpedantic -std=c89

autogenerated.o: autogenerated.c
	cc $(CFLAGS) -c autogenerated.c -o autogenerated.o

autogenerated.c: example
	./example

example: example.c core.h
	cc $(CFLAGS) example.c -o example

clean:
	@rm example
	@rm autogenerated.c
	@rm autogenerated.o
